name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true
          
      - name: Build for multiple platforms
        run: |
          # Build for Linux (amd64 and arm64)
          GOOS=linux GOARCH=amd64 go build -o ./build/fakessh-linux-amd64 ./cmd/fakessh
          GOOS=linux GOARCH=arm64 go build -o ./build/fakessh-linux-arm64 ./cmd/fakessh
          
          # Build for macOS (amd64 and arm64)
          GOOS=darwin GOARCH=amd64 go build -o ./build/fakessh-darwin-amd64 ./cmd/fakessh
          GOOS=darwin GOARCH=arm64 go build -o ./build/fakessh-darwin-arm64 ./cmd/fakessh
          
          # Build for Windows (amd64)
          GOOS=windows GOARCH=amd64 go build -o ./build/fakessh-windows-amd64.exe ./cmd/fakessh
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./build/fakessh-linux-amd64
            ./build/fakessh-linux-arm64
            ./build/fakessh-darwin-amd64
            ./build/fakessh-darwin-arm64
            ./build/fakessh-windows-amd64.exe
            ./config.yaml
            ./fakessh.service
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 